# Generated by Django 5.2.8 on 2025-11-07 10:10

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'customer',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=25)),
                ('dob', models.DateField()),
                ('email', models.CharField(max_length=50, unique=True)),
                ('gender', models.CharField(max_length=6)),
                ('address', models.CharField(max_length=225)),
                ('join_date', models.DateField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'employee',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('expense_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=9)),
            ],
            options={
                'db_table': 'expenses',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=255)),
                ('item_quantity', models.IntegerField()),
                ('minimum_stock_level', models.IntegerField()),
                ('status', models.CharField(max_length=19)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inventory',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_no', models.IntegerField()),
                ('date', models.DateField()),
                ('sdn_no', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'invoice',
                'managed': True,
            },
        ),
        # migrations.CreateModel(
        #     name='User',
        #     fields=[
        #         ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
        #         ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
        #         ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
        #         ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
        #         ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
        #         ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
        #         ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
        #         ('user_id', models.AutoField(primary_key=True, serialize=False)),
        #         ('username', models.CharField(max_length=150, unique=True)),
        #         ('email', models.EmailField(max_length=254, unique=True)),
        #         ('password', models.CharField(max_length=255)),
        #         ('role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('employee', 'Employee')], max_length=25)),
        #         ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
        #         ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
        #     ],
        #     options={
        #         'db_table': 'users',
        #         'managed': True,
        #     },
        #     managers=[
        #         ('objects', django.contrib.auth.models.UserManager()),
        #     ],
        # ),
        migrations.CreateModel(
            name='InventoryIssueLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_quantity', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.inventory')),
            ],
            options={
                'db_table': 'inventory_issue_log',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InvoiceItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.IntegerField()),
                ('item_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.invoice')),
            ],
            options={
                'db_table': 'invoice_items',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('po_no', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('site_name', models.CharField(max_length=255)),
                ('po_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(max_length=7)),
                ('project_status', models.CharField(max_length=9)),
                ('deadline', models.DateField()),
                ('customer', models.ForeignKey(blank=True, db_column='customer_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.customer')),
            ],
            options={
                'db_table': 'site',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='site',
            field=models.ForeignKey(db_column='site_name', on_delete=django.db.models.deletion.DO_NOTHING, to='api.site'),
        ),
        migrations.CreateModel(
            name='EmployeeSite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
                ('site', models.ForeignKey(db_column='po_no', on_delete=django.db.models.deletion.CASCADE, to='api.site')),
            ],
            options={
                'db_table': 'employee_site',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SiteExpenses',
            fields=[
                ('site_expense_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.expenses')),
                ('site', models.ForeignKey(db_column='po_no', on_delete=django.db.models.deletion.DO_NOTHING, to='api.site')),
            ],
            options={
                'db_table': 'site_expenses',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SiteProgressUpdate',
            fields=[
                ('progress_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('progress_details', models.TextField()),
                ('site', models.ForeignKey(db_column='po_no', on_delete=django.db.models.deletion.DO_NOTHING, to='api.site')),
            ],
            options={
                'db_table': 'site_progress_update',
                'managed': True,
                'unique_together': {('date', 'site')},
            },
        ),
    ]
